### ISSUE TITLE
Make aplpy conda install work with older numpy versions

### ISSUE THREAD

**Issue by cdeil** [astropy/conda-builder-affiliated#40] opened 2015-08-27 18:33 UTC
I'm trying to improve the Gammapy build matrix and am getting this issue in the builds testing against older numpy versions and installing the optional dependencies like aplpy:
https://travis-ci.org/gammapy/gammapy/jobs/77556117#L479

```
Hint: the following packages conflict with each other:
  - numpy 1.8*
  - aplpy
```

@astrofrog – Shouldn't aplpy work with Numpy 1.8?

Maybe the numpy version requirement isn't declared properly for the aplpy conda package?

**Comment by cdeil** [comment] 2015-08-27 18:36
Same issue with Numpy 1.6 and 1.7.
I updated the title to reflect the more general question / feature request.

**Comment by astrofrog** [comment] 2015-08-27 23:55
I thought it was possible to specify the dependency as `numpy > 1` and it would all with all Numpy versions, but I may be wrong.

**Comment by mwcraig** [comment] 2015-08-28 03:26
The problem is that conda used  to pin the numpy version when a package was built to the version of numpy installed in the build environment. The pinning was baked into the last part of the file name, e.g. `_np19py27`. That's great if you have a package that really needs a specific version of the numpy ABI, but not so helpful if the package handles a range of numpy versions.

This behavior was changed in a recent version of `conda-build`, so that it should be possible to build the affiliated packages in a numpy-version-agnostic way now. The alternative would be to maintain a complicated build matrix of numpy versions that would probably vary from package to package (i.e. not really an option).

Will _hopefully_ get a chance to fix it up this weekend -- if someone wants to take a crack at it before then, I think all that would be necessary is remove `CONDA_NPY` from the build matrix (see https://github.com/conda/conda-build/pull/493)

**Comment by cdeil** [comment] 2015-08-28 07:30
@mwcraig – Thanks!

If it doesn't work out, it's not a huge deal, it just complicates the setup of dependencies from my CI builds a bit, for end users just having one numpy version available should be sufficient (unless some of their packages pin it to different versions).

**Comment by mwcraig** [comment] 2015-09-16 03:07
@cdeil -- good news, all new builds of affiliated packages will not have the numpy version pinned unless the recipe or setup.py pins the numpy version. This is due to a change in conda build, and should simplify CI both for this and for astropy on older versions of numpy.

**Comment by mwcraig** [comment] 2015-09-16 03:08
@cdeil -- one other thought. If you want me to nuke the current aplpy builds and replace them with numpy agnostic versions, let me know. Wouldn't take much effort.

**Comment by mwcraig** [comment] 2015-12-10 03:33
@cdeil -- this is now fixed, finally...

**Closed as completed by mwcraig** 2015-12-10 03:33 UTC
